### ISSUE TITLE
PythonAI on PyPi

### ISSUE THREAD

**Issue by pplonski** [SpideyZac/DiscordBlocks#1]
I'm writing to you because you are the owner of PythonAI python package on PyPi https://pypi.org/project/PythonAI/ - I was trying to reach you by email but was bounced.

I would like to create an open-source package for safe execution of Python code generated by Large Language Models (for example ChatGPT). I would like to add safety check for which packages are imported and easy way for variables exchange between normal Python code and LLM generated code. I would like to name the package pythonai. 

If you are not planning to use it, would you mind freeing the `PythonAI` package name in PyPi? Just asking ...

All the best,
Piotr

**Comment by JustAnEric** [comment]
Choose a different name. I don't care what you're trying to create, just choose a different name.
